# Generated by Django 5.2.11 on 2026-03-03 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ngoiso', '0003_gallery'),
        ('users', '0003_alter_admin_admin_alter_admin_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('1', 'Priest'), ('2', 'Chair'), ('3', 'Catechist')], default='2', max_length=1),
        ),
        migrations.CreateModel(
            name='Catechist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='catechist_profile', to=settings.AUTH_USER_MODEL)),
                ('outstation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catechists', to='Ngoiso.outstation')),
            ],
        ),
    ]
