# Generated by Django 5.2.11 on 2026-03-03 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_user_type_catechist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Catechist',
        ),
    ]
