# Generated by Django 5.2.11 on 2026-03-04 09:34

import datetime
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('alt', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Jumuiya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Outstation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parish', models.CharField(choices=[('NGOISA', 'NGOISA PARISH')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='JumuiyaContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(default=2026)),
                ('amount', models.DecimalField(decimal_places=2, default=20000, max_digits=10, validators=[django.core.validators.MinValueValidator(20000)])),
                ('date_recorded', models.DateField(default=datetime.date.today)),
                ('jumuiya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ngoiso.jumuiya')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parish', models.CharField(choices=[('NGOISA', 'NGOISA PARISH')], max_length=50)),
                ('group', models.CharField(choices=[('CMA', 'CMA'), ('CWA', 'CWA'), ('YOUTH', 'Youth'), ('PMC', 'PMC')], max_length=50)),
                ('full_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=20)),
                ('jumuiya', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Ngoiso.jumuiya')),
                ('outstation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Ngoiso.outstation')),
            ],
        ),
        migrations.CreateModel(
            name='Mavuno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produce_type', models.CharField(choices=[('MAIZE', 'Maize'), ('BEANS', 'Beans'), ('WHEAT', 'Wheat'), ('MILLET', 'Millet'), ('COW', 'Ngombe'), ('GOAT', 'Mbuzi'), ('SHEEP', 'Kondoo'), ('CHICKEN', 'Chicken'), ('MONEY', 'Money'), ('OTHER', 'Other')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Use quantity for crops/animals or amount if MONEY', max_digits=10)),
                ('date_recorded', models.DateField(default=datetime.date.today)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ngoiso.member')),
            ],
        ),
        migrations.AddField(
            model_name='jumuiya',
            name='outstation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ngoiso.outstation'),
        ),
        migrations.CreateModel(
            name='Pledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('BUILDING', 'Church Building'), ('PROJECT', 'Special Project'), ('DEVELOPMENT', 'Parish Development'), ('EVENT', 'Church Event'), ('OTHER', 'Other')], max_length=50)),
                ('pledged_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date_pledged', models.DateField(default=datetime.date.today)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ngoiso.member')),
            ],
        ),
        migrations.CreateModel(
            name='Sadaka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('date_recorded', models.DateField(default=datetime.date.today)),
                ('outstation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ngoiso.outstation')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution_type', models.CharField(choices=[('ASSUMPTION', 'Assumption'), ('CHRISTMAS', 'Christmas'), ('PASAKA', 'Pasaka')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(150)])),
                ('date_recorded', models.DateField(default=datetime.date.today)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ngoiso.member')),
            ],
        ),
        migrations.CreateModel(
            name='Zaka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('JAN', 'January'), ('FEB', 'February'), ('MAR', 'March'), ('APR', 'April'), ('MAY', 'May'), ('JUN', 'June'), ('JUL', 'July'), ('AUG', 'August'), ('SEP', 'September'), ('OCT', 'October'), ('NOV', 'November'), ('DEC', 'December')], max_length=3)),
                ('year', models.PositiveIntegerField(default=2026)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('100.00'))])),
                ('date_recorded', models.DateField(default=datetime.date.today)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ngoiso.member')),
            ],
            options={
                'unique_together': {('member', 'month', 'year')},
            },
        ),
    ]
