# Generated by Django 5.2.11 on 2026-02-23 10:50

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jumuiya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Outstation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parish', models.CharField(choices=[('NGOISA', 'NGOISa Parish')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parish', models.CharField(choices=[('NGOISA', 'NGOISA Parish')], max_length=50)),
                ('group', models.CharField(choices=[('CMA', 'CMA'), ('CWA', 'CWA'), ('YOUTH', 'Youth'), ('PMC', 'PMC')], max_length=50)),
                ('full_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=20)),
                ('jumuiya', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Ngoiso.jumuiya')),
                ('outstation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Ngoiso.outstation')),
            ],
        ),
        migrations.CreateModel(
            name='Mavuno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produce_type', models.CharField(choices=[('MAIZE', 'Maize'), ('BEANS', 'Beans'), ('WHEAT', 'Wheat')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_received', models.DateField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ngoiso.member')),
            ],
        ),
        migrations.AddField(
            model_name='jumuiya',
            name='outstation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ngoiso.outstation'),
        ),
        migrations.CreateModel(
            name='Sadaka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('date_recorded', models.DateField(default=datetime.date.today)),
                ('outstation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ngoiso.outstation')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution_type', models.CharField(choices=[('NOEL', 'Noel'), ('CHRISTMAS', 'Christmas'), ('PASAKA', 'Pasaka')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paid', models.DateField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ngoiso.member')),
            ],
        ),
        migrations.CreateModel(
            name='Zaka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('A', 'Year A'), ('B', 'Year B'), ('C', 'Year C')], max_length=1)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paid', models.DateField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ngoiso.member')),
            ],
        ),
    ]
