# Generated by Django 5.2.11 on 2026-02-24 08:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ngoiso', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mavuno',
            name='date_received',
        ),
        migrations.RemoveField(
            model_name='specialcontribution',
            name='date_paid',
        ),
        migrations.RemoveField(
            model_name='zaka',
            name='date_paid',
        ),
        migrations.AddField(
            model_name='mavuno',
            name='date_recorded',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='specialcontribution',
            name='date_recorded',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='zaka',
            name='date_recorded',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
