# Generated by Django 5.2.11 on 2026-02-26 14:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ngoiso', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sadaka',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='specialcontribution',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(150)]),
        ),
        migrations.AlterField(
            model_name='specialcontribution',
            name='contribution_type',
            field=models.CharField(choices=[('ASSUMPTION', 'Assumption'), ('CHRISTMAS', 'Christmas'), ('PASAKA', 'Pasaka')], max_length=20),
        ),
    ]
