# Generated by Django 5.2.11 on 2026-02-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ngoiso', '0002_alter_specialcontribution_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialcontribution',
            name='contribution_type',
            field=models.CharField(choices=[('ASSUMPTION', 'Assumption'), ('CHRISTMAS', 'Christmas'), ('PASAKA', 'Pasaka')], max_length=20),
        ),
    ]
