# Generated by Django 5.2.11 on 2026-02-26 09:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ngoiso', '0003_alter_specialcontribution_contribution_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sadaka',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
